### PR TITLE
Persistence with string attributes

### PR DESCRIPTION
**Pull request by struktured**
This PR migrates over the `cas` and `eavi` modules from `holochain-core`. This consequently requires bringing over the `core_types_derive` crate to support the existing json serde framework. Thus `lib3h_persistence`, `lib3h_persistence_derive` crates are introduced. It makes no changes to the code except that 

 - `holochain_` occurrences are replaced by `lib3h_`
 - the `Attribute` enum is replaced by a type alias to `String`
 - validation of the attribute format is simplified and pushed downstream (previous code would validate link formats and such.)
 
This work was inspired and deduced by the SPIKE of issue #17. It addresses the persistence related crate  sharing between `holochain-core` and `lib3h` as noted in issue #35. The next step, assuming this PR is sound enough, is to migrate `cas_implementations` from `holochain-core` and make `holochain-core` build against it. 

Notes:

- `String` was favored over a generic trait to avoid complexity of lifetime parameters with `serde::Deserialize<'a>`. See https://circleci.com/gh/holochain/lib3h/95 and branch https://github.com/holochain/lib3h/tree/persistence-derive for details on this problem.
 - `String` was favored over an integer value to make it easier to support _dynamic_ attributes as needed by `holochain-core`. Eg. core has an attribute enum value called `LinkTag(String)` which would be difficult or error prone to map into an ordinal space.

### CODE REVIEW

**Comment by ddd-mtl** [comment]
Agree with @neonphog. I don't know whats the smoothest path onward, but it seems to me we would want in the end some kind of `foundation`  or `basic_types` crate, which has all the basic, dependencyless code: `JsonString`, `HashString`, `Timeout` etc.
And the Holochain specific basic types would stay in the `holochain-rust` repo somehow.

**Comment by struktured** [comment]
@neonphog @ddd-mtl I agree some of the holochain specific stuff should be moved out of this crate. I can do that before merging this in. As for the idea of shared / basic / foundational types, I would prefer to do that in another PR, if that's ok with the team- reason being it is probably a bit more involved to factorize them out.

**Comment by struktured** [comment]
@neonphog @ddd-mtl I removed a bunch of holochain specific modules and changed `HolochainError` to `PersistenceError`. I then removed the variants from the error enum that weren't relevant to persistence or at least not used by persistence crate. Take a look and let me know if this is sufficient!

**Comment by struktured** [comment]
Closing without merging in favor of #89  instead.

**Pull request closed without merging**
