### PR TITLE
lib3h upgraded to use ghost actor awesomeness!!!

### PR DESCRIPTION
**Pull request by neonphog**
## PR summary

:ghost:

Lib3h components use GhostActors to implement asynchrnous message passing and coordination.

## Review checklist 
- [x] The story has unit or integration tests
- [ ] No new bugs, and any tech-debt is identified and justified
- [ ] There is enough API documentation (how to use)
- [ ] There is enough code documentation (how the code works)

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@neonphog how come not riker or similar?

**Comment by neonphog** [comment]
@thedavidmeister 

> @neonphog how come not riker or similar?

I did some evaluation of other rust actor systems, and came to the conclusion that they're solving different problems, and not necessarily exclusive ones. We could potentially still use Riker or the more popular Actix for the memory management / message routing aspect. But for the moment, there's no problem with actors directly owning sub-actors in lib3h.

GhostActor is solving the problem of ergonomic response handling to requests that go out and potentially return asynchronously, without having to pull in Futures.

**Comment by thedavidmeister** [comment]
@neonphog ok cool, FYI @maackle

**Comment by pegaltier** [comment]
congrats team!

**Comment by pegaltier** [comment]
holochain-kamehameha

**Pull request merged**
